---
- hosts: localhost
  connection: local
  gather_facts: no


  roles:
    - role: "avinetworks.avisdk"

  tasks:

    - name: Create Backup Configuration passphrase
      avi_backupconfiguration:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        state: present
        backup_passphrase: "{{ avi_credentials.password }}"
        name: Backup-Configuration
        save_local: true
      tags:
        - system

    - name: Configure Avi System parameters
      avi_systemconfiguration:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        global_tenant_config:
          se_in_provider_context: "{{ controller.se_in_provider_context | default('false') }}"
          tenant_access_to_provider_se: "{{ controller.tenant_access_to_provider_se | default('true') }}"
          tenant_vrf: "{{ controller.tenant_vrf | default('false') }}"
        dns_configuration:
          search_domain: ''
          server_list: "{{ controller.dns }}"
        ntp_configuration:
          ntp_servers: "{{ controller.ntp }}"
        email_configuration:
          from_email: "{{ controller.email_configuration | default('test@avicontroller.net') }}"
          smtp_type: SMTP_LOCAL_HOST
        welcome_workflow_complete: true
      tags:
        - system
